<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\InteractionFlow.Core\InteractionFlow.Core.csproj" />
		<ProjectReference Include="..\InteractionFlow.Standard\InteractionFlow.Standard.csproj" />
		<ProjectReference Include="..\InteractionFlow.Analyzers\InteractionFlow.Analyzers.csproj"
						  OutputItemType="Analyzer"
						  ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>
