<Project Sdk="Microsoft.NET.Sdk">	<PropertyGroup>		<TargetFramework>netstandard2.1</TargetFramework>	</PropertyGroup>	<ItemGroup>		<ProjectReference Include="..\InteractionFlow.Core\InteractionFlow.Core.csproj" />		<ProjectReference Include="..\InteractionFlow.Standard\InteractionFlow.Standard.csproj" />		<ProjectReference Include="..\InteractionFlow.Analyzers\InteractionFlow.Analyzers.csproj"						  OutputItemType="Analyzer"						  ReferenceOutputAssembly="false" />	</ItemGroup></Project>
