<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<PackageId>InteractionFlow.Analyzers</PackageId>
		<VersionPrefix>$(AnalyzerVersion)</VersionPrefix>
		<Description>$(DescriptionHead)特に、アーキテクチャの規則を静的に解析して警告するアナライザーライブラリを提供します。</Description>
		<PackageTags>$(PackageTags);analyzer;roslyn;diagnostics;architecture-rules</PackageTags>
		<PackageReleaseNotes>Interaction Flow Architecture の依存関係ルールを検証する Analyzer 0.4.1 リリースです。</PackageReleaseNotes>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
		<IncludeSymbols>false</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers"
						  Version="2.9.8"
						  PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp"
						  Version="3.3.1"
						  PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(OutputPath)$(AssemblyName).dll"
			  Pack="true"
			  PackagePath="analyzers/dotnet/cs"
			  Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources.ja.resx">
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.resx"
						  Generator="ResXFileCodeGenerator">
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
