//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractionFlow.Analyzers {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InteractionFlow.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Interaction Flow Implementation Rule - Invalid dependency node declaration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DependencyNodeAnalyzerDescription {
            get {
                return ResourceManager.GetString("DependencyNodeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid dependency node declaration ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DependencyNodeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("DependencyNodeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid dependency node declaration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DependencyNodeAnalyzerTitle {
            get {
                return ResourceManager.GetString("DependencyNodeAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDependencyNode class must be sealed or declare &apos;params IDependencyNode[] dependency&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DependencyNodeMustBeSealedOrHaveParams {
            get {
                return ResourceManager.GetString("DependencyNodeMustBeSealedOrHaveParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter &apos;{0}&apos; must be included in Dependency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DependencyNodeParameterMustBeIncludedInDependency {
            get {
                return ResourceManager.GetString("DependencyNodeParameterMustBeIncludedInDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter &apos;{0}&apos; must be passed to the base IDependencyNode constructor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DependencyNodeParameterMustBePassedToBase {
            get {
                return ResourceManager.GetString("DependencyNodeParameterMustBePassedToBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interaction Flow Architecture Rule - Invalid layer dependency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDependencyAnalyzerDescription {
            get {
                return ResourceManager.GetString("LayerDependencyAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid layer dependency ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDependencyAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LayerDependencyAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid layer dependency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDependencyAnalyzerTitle {
            get {
                return ResourceManager.GetString("LayerDependencyAnalyzerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Layer &apos;{0}&apos; must not depend on &apos;{1}&apos; (Type = &apos;{2}&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDependencyDisallowedReference {
            get {
                return ResourceManager.GetString("LayerDependencyDisallowedReference", resourceCulture);
            }
        }
    }
}
